[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if G.SETTINGS.skip_splash == 'Yes' then"
position = "at"
payload = "if true then"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.GAME = saveTable and saveTable.GAME or self:init_game_object()'''
position = "at"
payload = '''
self.GAME = saveTable and saveTable.GAME or self:init_game_object()
self.RE = {}
self.RE.earnings = {}
self.RE.shop = false
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.FUNCS.evaluate_round = function()"
position = "at"
payload = '''
G.FUNCS.evaluate_round = function()
    G.RE.earnings = {}
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
                G.VIBRATION = G.VIBRATION + 1
                return true
            end
        }))
    end
end
'''
position = "at"
payload = '''                G.VIBRATION = G.VIBRATION + 1
                return true
            end
        }))
    end
    G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        no_delete = true,
        func = function()
            table.insert(G.RE.earnings, config)
            return true
        end
    }))
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
G.CONTROLLER:snap_to({node = G.shop:get_UIE_by_ID('next_round_button')})
if not nosave_shop then G.E_MANAGER:add_event(Event({ func = function() save_run(); return true end})) end
return true
'''
position = "at"
payload = '''
G.CONTROLLER:snap_to({node = G.shop:get_UIE_by_ID('next_round_button')})
if not nosave_shop then G.E_MANAGER:add_event(Event({ func = function() save_run(); return true end})) end
G.RE.shop = true
return true
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "function/button_callbacks.lua"
pattern = '''
G.FUNCS.toggle_shop = function(e)
'''
position = "at"
payload = '''
G.FUNCS.toggle_shop = function(e)
sendTraceMessage("reset shop")
G.RE.shop = false
'''
match_indent = true
times = 1