[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if G.SETTINGS.skip_splash == 'Yes' then"
position = "at"
payload = "if true then"
match_indent = true
times = 1
